README.md
package.json
scripts/publish_prod.sh
yarn.lock

This PR adds badges to the readme and instructs the customer to download the CDK through yarn.
Previously the customer had to download the CDK by cloning the entire GitHub repository, now they can simply download the package from Yarn or NPM.
I was able to download the cdk constructs on a local project successfully using the 'yarn add --dev datadog-cdk-constructs' command.
I created a test CDK project which used the NPM and Yarn DD-CDK-constructs download commands and was able to successfully view a lambda function in datadog with logs, metrics, and traces after deploying with CDK

datadog-cdk-constructs Yarn/NPM download command

---

package.json
yarn.lock

Reverts DataDog/datadog-cdk-constructs#16

Revert "aws-cdk packages as peer dependencies"

---

.projen/deps.json
.projenrc.js
package.json
src/datadog.ts
src/sample/index.ts
src/sample/lambda_nodejs/hello_node.js
test/index.spec.ts
yarn.lock

Enables the datadog cdk construct to accept lambda functions instantiated with the [aws-cdk-lambda-nodejs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda-nodejs.NodejsFunction.html) construct.
Part of ongoing work to update the construct and enabling Nodejs and Python constructs 
https://datadoghq.atlassian.net/browse/SLS-1420
Updated the `index.spec.ts` to test for when users use a mix of Lambda.Function or NodejsFunction types.

Support for NodejsFunction construct

---

.github/workflows/build.yml

Updates the github workflow to login to ECR and pull a required public Docker image
Updates to the library using the PythonFunction construct require Docker and are blocking tests from passing:
```
Step 1/4 : ARG IMAGE=public.ecr.aws/sam/build-python3.7
Step 2/4 : FROM $IMAGE
toomanyrequests: Rate exceeded
```

Updating github workflow

---

integration_tests/lambda/example-python.py
integration_tests/snapshots/correct-lambda-function-stack-snapshot.json
integration_tests/snapshots/correct-lambda-nodejs-function-stack-snapshot.json
integration_tests/snapshots/correct-lambda-python-function-stack-snapshot.json
integration_tests/snapshots/test-lambda-function-stack-snapshot.json
integration_tests/snapshots/test-lambda-nodejs-function-stack-snapshot.json
integration_tests/snapshots/test-lambda-python-function-stack-snapshot.json
integration_tests/stacks/lambda-function-stack.ts
integration_tests/stacks/lambda-nodejs-function-stack.ts
integration_tests/stacks/lambda-python-function-stack.ts
scripts/run_integration_tests.sh

Expands existing integration tests to include the PythonFunction construct
https://datadoghq.atlassian.net/browse/SLS-1186

Expanded integration tests

---

.github/workflows/integration_tests.yml
.projen/deps.json
.projenrc.js
integration_tests/snapshots/correct-lambda-function-arm-stack-snapshot.json
integration_tests/snapshots/correct-lambda-nodejs-function-stack-snapshot.json
integration_tests/snapshots/correct-lambda-python-function-stack-snapshot.json
integration_tests/snapshots/test-lambda-function-arm-stack-snapshot.json
integration_tests/snapshots/test-lambda-nodejs-function-stack-snapshot.json
integration_tests/snapshots/test-lambda-python-function-stack-snapshot.json
integration_tests/stacks/lambda-function-arm-stack.ts
package.json
scripts/run_integration_tests.sh
src/datadog.ts
src/layer.ts
src/transport.ts
test/datadog.spec.ts
test/layer.spec.ts
yarn.lock

Update support for Lambda architectures. This required a dependency bump.
Removed the `architecture` field from our settings and now we are reading it from the aws-cdk `Function` interface.
AWS-CDK not supporting the architecture field, once released the latest version (`1.134.0`), it was possible for us to update the support for architectures properly.
Modified existing tests.

Update ARM support

---

README.md

Reverts DataDog/datadog-cdk-constructs#73

Revert "Remove docs for Secrets Manager"

---

common/scripts/fix-version.js

Address the last comment in [this PR](https://github.com/DataDog/datadog-cdk-constructs/pull/84). Added a check in fix-version.js (ran within the package build process), preventing wrong arguments.
Manually tested building when less arguments, more arguments, incorrect arguments.

throw error if argument count is wrong (fix-version.js)

---

v1/README.md
v2/README.md

Soft-linked the readme in the repo root into the v1 and v2 folders, replacing the placeholder readme files that projen auto generated.
Upon publishing the new v2 package, we realized that npm and pypi was pulling the wrong readme for the package pages. The readme file within the v2 folder was being used, rather than the readme in the root of the repo. If we publish a new version of v1, the same behavior will occur.
We've decided this is not urgent enough to warrant a hotfix. Fix will be applied upon release of a new version of `datadog-cdk-constructs-v2` in the future

Fixed wrong readme displayed for published npm, pypi packages

---

README.md

This PR adds docs for the source code integration feature.

Add source code integration documentation

---

common/constants.ts
v2/.projen/deps.json
v2/.projenrc.js
v2/integration_tests/snapshots/correct-lambda-function-arm-stack-snapshot.json
v2/integration_tests/snapshots/correct-lambda-function-stack-snapshot.json
v2/integration_tests/snapshots/correct-lambda-nodejs-function-stack-snapshot.json
v2/integration_tests/snapshots/correct-lambda-python-function-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-function-arm-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-function-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-nodejs-function-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-python-function-stack-snapshot.json
v2/package.json
v2/test/datadog.spec.ts
v2/test/env.spec.ts
v2/test/forwarder.spec.ts
v2/test/index.spec.ts
v2/test/layer.spec.ts
v2/test/transport.spec.ts
v2/yarn.lock

- Updates the aws-cdk-lib dependency for Node16 support
- Updates unit tests
- Update snapshots
Node 16 
Unit & Integration tests

Update dependencies for Node16 support

---

README.md

Update the instructions to enable the source code integration with the latest version of https://github.com/DataDog/datadog-ci
Starting with [datadog-ci@v1.13.0](https://github.com/DataDog/datadog-ci/releases/tag/v1.13.0), the interface of `uploadGitCommitHash` changed, to also return the repository URL.

Update datadog-ci instructions to latest version

---

v1/scripts/publish_prod.sh
v2/scripts/publish_prod.sh

Updates the authentication method and instructions to use our newly created tokens.

Update authentication method for PyPI

---

README.md

Removes a badge which says "undefined", there's a link to slack lower in the readme anyway.

Remove slack badge from readme

---

v2/src/layer.ts
v2/test/layer.spec.ts

Fixes bug where the CDK would error if the architecture property of the Lambda was undefined
https://github.com/DataDog/datadog-cdk-constructs/issues/171
Added a test

Fix bug in ARM check

---

common/constants.ts

feat: add java17 in runtimeLookup

---

README.md

Docs for [this PR](https://github.com/DataDog/datadog-cdk-constructs/pull/178)
These changes have been included in the `v2-1.7.1` release.

Auto Grant Secret Read Access Docs

---

README.md

adds cdk v1 deprecation warning, link migration guide

Add cdk v1 end of support warning

---

v2/integration_tests/snapshots/correct-lambda-function-arm-stack-snapshot.json
v2/integration_tests/snapshots/correct-lambda-function-stack-snapshot.json
v2/integration_tests/snapshots/correct-lambda-java-function-stack-snapshot.json
v2/integration_tests/snapshots/correct-lambda-nodejs-function-stack-snapshot.json
v2/integration_tests/snapshots/correct-lambda-python-function-stack-snapshot.json
v2/integration_tests/snapshots/correct-lambda-singleton-function-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-function-arm-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-function-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-java-function-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-nodejs-function-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-python-function-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-singleton-function-stack-snapshot.json

Updates snapshots to account for new ASM env var
Noticed these were failing after merging ASM
Tests should now be passing

Update integration test snapshots for ASM

---

README.md

I add a syntax highlight to typescript code in README.md.
When I read the README.md, I noticed that syntax highlights was not working on the code.

docs: Add code syntax highlight

---

v2/.projen/deps.json
v2/.projenrc.js
v2/package.json
v2/yarn.lock

Upgrades a dev dependency missed on #227.
I forgot to upgrade it on the merge conflict.
n/a

chore: upgrade dev dependency `@aws-cdk/aws-lambda-python-alpha`

---

examples/python-stack/cdk_python/cdk_python_stack.py
examples/python-stack/requirements.txt
examples/typescript-stack/lib/cdk-typescript-stack.ts
examples/typescript-stack/package.json
examples/typescript-stack/yarn.lock
v2/.github/workflows/pull-request-lint.yml
v2/.github/workflows/upgrade.yml
v2/.gitignore
v2/.npmignore
v2/.projen/deps.json
v2/.projen/tasks.json
v2/.projenrc.js
v2/package.json
v2/src/constants.ts
v2/test/redirect.spec.ts
v2/tsconfig.dev.json
v2/yarn.lock

Supports .NET 8
Widely available as a new AWS Lambda Runtime.
- updated unit test
- CDK synth locally
- Had to update dependencies for this to work.
- Also updated examples.

feat: support .NET 8 runtime

---

examples/python-stack/requirements.txt
examples/typescript-stack/package.json
examples/typescript-stack/yarn.lock

Updates examples dependencies to use latest released version of this package.
So the example can use the latest runtimes.
`cdk synth` working

chore: update examples dependencies

---

scripts/publish_prod.sh

In `publish_prod.sh`, add the command for publishing the Go package.
Right now `publish_prod.sh` covers publishing to npm and PyPI. As the support for Go CDK Construct was just added, we should add the Go publish command to the script so that whenever we want to release a new version, the Go package will be updated as well.
1. Create a test script `publish_prod_go_test.sh` which only contains the added lines:
```
#!/bin/bash
echo "Publishing the Go package to datadog-cdk-constructs-go GitHub repo"
read -p "Please enter your GitHub username: " GITHUB_TOKEN
GITHUB_TOKEN=$GITHUB_TOKEN npx -p publib@latest publib-golang
```
2. Run the script
The Go package was published successfully
```
yiming.luo@COMP-J7WRL6274T datadog-cdk-constructs % cat scripts/publish_prod_go_test.sh
#!/bin/bash
echo …
```

chore: add the script to publish Go module

---

examples/go-stack/app.go

Right now `NewAppStack()` creates a stack and integrates it with Datadog. This PR splits into two functions:
1. `NewAppStackWithoutDatadog()`: creates a stack, without Datadog integration
2. `NewAppStackWithDatadog()`, which calls `NewAppStackWithoutDatadog()` and adds Datadog integration
I'm going to rename the interfaces like I did in https://github.com/DataDog/datadog-cdk-constructs/pull/288. To make sure both the new API and old API work, I will need to to write two stacks for testing the two APIs. The two stacks will share the non-Datadog setup code, so I'm putting this part in the `NewAppStackWithoutDatadog()` function.
`cdk deploy` successfully deploys the Go stack.

chore: Refactor example Go stack by splitting a function

---

examples/python-stack/README.md
examples/step-functions-python-stack/README.md
examples/step-functions-python-stack/app.py
examples/step-functions-python-stack/cdk.json
examples/step-functions-python-stack/cdk_step_functions_python_stack.py
examples/step-functions-python-stack/requirements.txt

Add an example Python stack that creates and instruments a State Machine.
Deployed the stack, and the traces showed up in Datadog app.

feat: Add example Python stack for Step Functions

---

integration_tests/snapshots/correct-step_functions_python_stack-snapshot.json
integration_tests/stacks/python/step_functions_python_stack.py
scripts/run_integration_tests.sh

Add a snapshot test for a Python step function stack to ensure future changes don't unintentionally change the synthesized CloudFormation template.

chore: Add snapshot test for Python step function stack

---

examples/step-functions-typescript-stack/README.md

Step Function support is complete, so this PR updates the README for TypeScript stack so users can play around with it.
Tested that this stack works.

chore: Update README for Step Functions TypeScript stack

---

README.md

As @nine5two7 suggested in this comment (https://github.com/DataDog/datadog-cdk-constructs/pull/338#discussion_r1858994327), add guidance for disabling tracing for step functions.
@cswatt Let's also explain in external doc that we enable tracing for Step Functions by default; they have these options if they want to disable tracing.

chore: Update Step Function doc about tracing

---

README.md

Update README regarding how to import the Go package under the new major version.

chore: Update README on how to import Go package

---

.github/CODEOWNERS

Set `container-platform` team as CODEOWNER of ECS code

chore: Set container-platform as CODEOWNER of ECS code

---

README.md

Update documentation to point root README to ECS Fargate docs.
Users can easily be aware of ECS Fargate construct within the Datadog CDK Constructs repo.
N/A
Future work to be done:
Create a top level structure with the READMEs. Have the root highlight basic install info for the module and then direct to other more detailed READMEs for each different construct.

chore: Fargate docs update

---

integration_tests/snapshots/correct-ecs-fargate-stack-snapshot.json
scripts/run_integration_tests.sh

Updates the ecs fargate snapshot integration tests.
CI is being updated to allow external contributions run on the full CI.

fix: Update Integration Tests for Fixed DockerLabels

---

src/apigateway/README.md

Adds a README file to help customers install API Gateway tracing.
https://datadoghq.atlassian.net/browse/APMSVLS-19  
https://datadoghq.atlassian.net/browse/APMSVLS-41

chore: add apigateway README file

---

README.md

Updates readme because function-specific environment variables will no longer be overridden by the datadog-lambda constructor.
[SVLS-6594](https://datadoghq.atlassian.net/browse/SVLS-6594)
[SVLS-6594]: https://datadoghq.atlassian.net/browse/SVLS-6594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update README for lambda function environment variable override changes
