DataDog/datadog-cdk-constructs

package.json
yarn.lock

This PR makes the aws-cdk construct libraries needed in the datadog-cdk-constructs to be peer dependencies. This should keep versions of the cdk libraries in sync with customer's cdk applications dependencies. 
For example lets say a customer has a cdk project that uses `aws-cdk/core` v1.65.0 but Datadog's-cdk-constructs require `aws-cdk/core` v1.71.0 and above, well then the package manager should fail the installation of the Datadog-cdk-constructs because it has an unmet peer dependency.
I built and created a local package of the datadog-cdk-constructs library using `npm build` and `npm pack` this created a zip file of the dd-cdk-constructs (with the updated peer dependencies). From there I copied the cdk zip into my [lambda-cdk-constructs-demo](https://github.com/DataDog/cloud-integrati …

aws-cdk packages as peer dependencies

---

README.md

Makes documentation references to `forwarderARN` consistent with the TS interface in the code.
Lazy people like me who copy / paste options from the README see a TS error related to `forwarderARN` due this casing difference.
N/A
N/A

(fix): Fix casing of forwarderARN references in README

---

lib/forwarder.ts
lib/layer.ts
test/index.spec.ts

This PR changes the logic for the creation of the `forwarder`, `subscriptionFilter`, and `layer` constructs in an attempt to never create duplicate constructs in the same cdk construct tree while also methodically creating new constructs only when necessary.
A customer ran into this error `There is already a Construct with name 'forwarder' in ...`. After doing some research I was able to reproduce the error by creating a unit test that created a mock aws-cdk app, stack, and constructs related to the Datadog-cdk-construct library. This unit test intentionally called the `addForwarder` function twice. I am not sure if this is exactly how the customer encountered this problem but I believe my solution should prevent it from happening again.
Before both `addForwarder` calls our construct tree …

Duplicate Constructs Bug 🐛

---

README.md

Fixes typo in README `enable_dd_tracing` should be `enable_datadog_tracing`,  this PR also adds a PyPI badge.
Manually walked through all the parameters to make sure they were all correct for the respective packages.

Fix README typo and add PyPI badge

---

src/forwarder.ts
src/lambdaDestination.ts

Fixes: [SLS-1075](https://datadoghq.atlassian.net/jira/software/projects/SLS/boards/205?selectedIssue=SLS-1075)
Implements `ILogSubscriptionDestination` as `LambdaDestination` but removes the logic of adding Lambda Permissions. While we wait for this aws-cdk [PR](https://github.com/aws/aws-cdk/pull/14222)  to merge I implemented the class locally to fix the policy length problem. The local class can be removed and used in favor with `import { LambdaDestination } from "@aws-cdk/aws-logs-destinations";` once the AWS-CDK PR is merged and released. **Or if we decide this can wait we can simply put [SLS-1075](https://datadoghq.atlassian.net/jira/software/projects/SLS/boards/205?selectedIssue=SLS-1075) on blocked until AWS-CDK merges and releases the fixes.**
Customers ran into issues with the …

Fix Policy Length error when using a large number of lambda functions

---

src/forwarder.ts
test/forwarder.spec.ts
test/index.spec.ts
test/test-utils.ts

This PR calls ensures the log filter subscription resource id does not change on subsequent cdk deploys.
Every time I deploy my app utilizing datadog-cdk-constructs, I see that the log subscription filters are deleted and re-added by CloudFormation. This due to references being passed in as the functionArn to generateForwaderConstructId, and the reference ID numbers are not stable across synth operations. See below for back-to-back cdk diff operations:
An additional unit test was added that shows two identical -- but independent -- stacks produce the same name of the subscription filter, but a third stack with a differently named resource does not.
The implementation of the existing unit tests inlined the actual id generation algorithm, so I modified these tests to instead introspect the …

Ensure log group subscription filter resource has stable id

---

src/env.ts
test/env.spec.ts

This corrects the `DD_LOG_INJECTION` env var to `DD_LOGS_INJECTION`. The variable is set when a user passes `injectLogContext: true` to the Datadog constructor. Both the [JS](https://github.com/datadog/datadog-lambda-js#dd_logs_injection) and [Python](https://github.com/datadog/datadog-lambda-python#dd_logs_injection) libraries expect `DD_LOGS_INJECTION`.
This fixes issue #35 
This is not a breaking change, since this has been incorrect since the beginning.
`DD_LOG_INJECTION` -> `DD_LOGS_INJECTION`
#35

Fix DD_LOGS_INJECTION env var

---

.eslintrc.json
.projenrc.js
src/datadog.ts
test/datadog.spec.ts

This PR adds a CDK Version tag to each Lambda Function that is instrumented via the DD CDK Construct Library.
With [SLS-1077](https://datadoghq.atlassian.net/jira/software/projects/SLS/boards/205?selectedIssue=SLS-1077) we would like to track the number of lambdas instrumented via the DD CDK with our [AWS Lambda Metadata Crawler](https://github.com/DataDog/devops/wiki/AWS-Lambda-Metadata-Crawler) and eventually have it populated in [this](https://app.datadoghq.com/dashboard/j8t-8s6-n2i/serverless-kpi-dashboard?from_ts=1618955916530&fullscreen_end_ts=1619042316530&fullscreen_paused=true&fullscreen_start_ts=1618955916530&fullscreen_widget=3730893819089948&live=false&tile_focus=3730893819089948&to_ts=1619042316530&fullscreen_section=overview) dashboard. 
The first step to get that working is …

Add `dd_cdk_construct` tag to all lambda functions deployed via the DD CDK Construct

---

scripts/publish_prod.sh

This PR attempts to make the release script more rigid. For instance:
* I strengthened the regex to only allow digits. (When someone would call the script using `v3.1.4` it would fail because many of the commands later in the script did not expect there to be a `v` just strictly the `major.minor.patch`)
* Before going any further in the script we check to make sure the user has all the necessary terminal commands as that would be a silly way to end the script. One instance I am trying to avoid is the JS package being published but then the Python one fails because they dont have `pip` or `python3`. I would like to minimize the chance that the script fails in a critical part like the publishing to NPM and PyPi.
* Before publishing the artifacts we make sure that they actually exist. This …

Improve Release Script

---

README.md
test/index.spec.ts

This PR documents how to enable the DD CDK Construct on nested stacks.
We got a feature request for nested stacks in [SLS-1104](https://datadoghq.atlassian.net/jira/software/projects/SLS/boards/205?selectedIssue=SLS-1104). However after some testing I concluded that nested stacks are supported, the user just has to re-add the Datadog CDK Construct to each stack whether or not its a nested or regular CDK stack.
Checkout [this](https://dd.slack.com/archives/GHQ114DRR/p1620164676032100) slack thread for more context on why we decided to just document the current way of using nested stacks.
I manually created nested stacks and made sure the DD CDK Construct worked on both by checking out the deployed resources.
I also added a test which asserts that forwarder log group subscriptions/DD Lambda …

Document Nested Stack support

---

scripts/publish_prod.sh

This PR moves the `pip install --upgrade twine` command to a less critical part of the publish script.
While pairing with team members to make a release to the DD CDK we encountered an issue with the release script, the pip version I used to create the script was different than the version the person running the script was using that caused the `pip install --upgrade twine` command to prematurely terminate the script because it couldn't find `twine`.
Having the possibility that the script can fail after publishing to npm but before publishing to PyPi could cause issues. Therefore in order to minimize the chance that that happens I think its a better idea to move the pip install command higher in the script so that if it fails it wont be at a critical part of the script. 
I tried to add …

Improve publish script by moving pip command earlier in script

---

src/datadog.ts
src/forwarder.ts
test/forwarder.spec.ts

When using aws-logs `from` functions, such as `fromLogGroupName`, an ILogGroup is returned. This PR changes `addForwarderToLogGroups` to use an `ILogGroup` parameter instead of a `LogGroup`, creating compatibility with imported log groups.
I've also corrected a minor spelling typo.
I wanted to use the construct with imported log groups.
Added unit test.

Allow usage of addForwarderToLogGroups on log groups imported using from functions

---

.github/workflows/build.yml

Previously, we ran the unit tests against Node 10, 12, and 14. Node 10 reached end of life on April 30, 2021 and is no longer receiving any updates. Meanwhile, the current version of Node is 16, and will become the LTS release on October 26, 2021. We should adjust which versions we test against accordingly.
See [here](https://nodejs.org/en/about/releases/) for more information about Node versions.

Stop testing against Node 10, start testing against Node 16

---

src/layer.ts

- Add support for the Python 3.9 runtime
- Remove support for Node 8.10 runtime. This is not a breaking change because it has not been possible to update or create a Lambda function using this runtime since March 6, 2020.

Add support for Python 3.9

---

integration_tests/snapshots/correct-lambda-function-arm-stack-snapshot.json
integration_tests/snapshots/test-lambda-function-arm-stack-snapshot.json
src/layer.ts
test/layer.spec.ts

Removes -ARM from the Node layer when `ARM_64` is enabled since it is not required.
Unit and Integration

Remove -ARM suffix from the layer of Node runtime types

---

README.md
src/transport.ts

This reverts commit 116f78ca797babccc6713c820847f8722ff3457d.
Revert a commit which adds the documentations for [DataDog/datadog-cdk-constructs#72](https://github.com/DataDog/datadog-cdk-constructs/pull/72).
Not releasing CDK until we fix support for Graviton 2.
N/A
This PR should be reverted once the motivation is completed.

Remove docs for Secrets Manager

---

common/env.ts
v1/src/datadog.ts
v1/test/env.spec.ts
v2/src/datadog.ts
v2/test/env.spec.ts

This PR adds a new public function to the CDK that is to be called by the user to add git metadata to their lambda. Unfortunately due to CDK constraints we were unable to do this automatically and it requires the user to call an additional function to enable this feature. This feature should be used by importing `@datadog/datadog-ci` and passing in the results of `uploadGitMetadata` to `addGitCommitMetadata`. Documentation will be added in a future PR.
This feature is optional and is not a breaking change.
Adds support for source code integration.
This feature has unit tests.

SLS-1692: Add source code integration feature for v1 and v2 CDK

---

v1/scripts/publish_prod.sh
v2/scripts/publish_prod.sh

Previously, both v1 and v2 `publish_prod.sh` release scripts would abort if the previous commit was a release (if the previous commit's message started with `chore(release):`). 
This PR adds the option to continue anyways.
Previously If you want to publish v1 and v2 packages consecutively, you would need to create a dummy commit before releasing the second package. This fixes that.

Allow consecutive releases

---

v1/scripts/publish_prod.sh
v2/scripts/publish_prod.sh

Makes the deployment message more clear to account for the case where we're deploying v1 and then immediately after, v2.

Make deployment message clearer

---

v2/.projen/deps.json
v2/.projenrc.js
v2/package.json
v2/yarn.lock

Bumps the construct peerdep to @aws-cdk/aws-lambda-python-alpha@^2.24.0-alpha.0
This should fix https://github.com/DataDog/datadog-cdk-constructs/issues/91
Deployed successfully with a demo TS CDK app and `"@aws-cdk/aws-lambda-python-alpha": "^2.24.0-alpha.0"`

Bump @aws-cdk/aws-lambda-python-alpha@ to ^2.24.0-alpha.0

---

common/env.ts
v2/test/env.spec.ts

Fixes overwriting DD_TAGS when sourceCodeIntegration is enabled.
Unit tested
Unfortunately I've had to use an `any` type as the aws `Function` class has `environment` as a private field which we cannot overwrite.

SLS-2345: Fix overwriting DD_TAGS when using source code integration

---

README.md
common/interfaces.ts
v2/src/datadog.ts
v2/src/forwarder.ts
v2/src/sample/index.ts
v2/test/forwarder.spec.ts

See #124 
The default behavior of the `LambdaDestination` AWS Log Group CDK construct is to [create a permission on the destination lambda](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_logs_destinations.LambdaDestinationOptions.html#addpermissions). While this may be desirable in many cases, the Datadog Forwarder already has permission set to allow log groups to forward their logs. Therefore, this default behavior is entirely unnecessary and problematic.
Stacks with large number of Lambdas, and therefore log groups, get resource quota exceeded errors trying to deploy with a Datadog Forwarder. If a stack is split up so there are fewer resources, then a new error shows up: `The final policy size [for the Datadog Forwarder] ({{ size }}) is bigger than the limit (20480)`. This …

Default to Not Create Forwarder Permissions

---

v2/src/layer.ts

Fix comparison of `lam.architecture` and `Architecture.ARM_64`.
`Architecture.ARM_64` is an object and not ENUM.
Currently, it fails to fetch ARM layers from Datadog causing runtime errors in Lambdas.
Ran `yarn test` in v2.
We can also check Lambdas architecture like this:
`const isARM = lam.architecture.name === Architecture.ARM_64.name;`
or 
`const isARM = lam.architecture.dockerPlatform === Architecture.ARM_64.dockerPlatform;`
Not sure what you'd prefer;

fix: isARM object comparison

---

README.md
common/env.ts
v1/src/datadog.ts
v1/test/env.spec.ts
v2/src/datadog.ts
v2/test/env.spec.ts

Updates the CDK to tag lambda functions with the git repo url alongside the git commit sha. Removes git metadata uploading.
Preserves the legacy way of adding SCI (metadata uploading)
the v1 and v2 env.ts unit test files were out of sync, some tests were in different orders, or missing in one test and included in the other. Slightly refactored this test file, so the tests are more in parity. Updated tests to check for git repo tagging.
- README will be updated in a future PR (after the cdk releases)
New Source Code Integration implementation guidelines, steering away from using git metadata upload.
Updated unit tests. Manually used the local version of the cdk to deploy test stacks, testing both using the legacy implementation, and this new one (requiring users to import datadog-ci …

Update source code integration, git repo tagging

---

common/constants.ts
common/datadogSharedLogic.ts
common/env.ts
common/interfaces.ts
v1/integration_tests/stacks/lambda-function-arm-stack.ts
v1/integration_tests/stacks/lambda-function-stack.ts
v1/integration_tests/stacks/lambda-nodejs-function-stack.ts
v1/integration_tests/stacks/lambda-python-function-stack.ts
v1/src/datadog.ts
v1/test/env.spec.ts
v1/test/index.spec.ts
v1/test/transport.spec.ts
v2/integration_tests/stacks/lambda-function-arm-stack.ts
v2/integration_tests/stacks/lambda-function-stack.ts
v2/integration_tests/stacks/lambda-nodejs-function-stack.ts
v2/integration_tests/stacks/lambda-python-function-stack.ts
v2/src/datadog.ts
v2/test/env.spec.ts

uses `execSync` from node's `child_processes` module to synchronously call `git rev-parse HEAD` and `git config --get remote.origin.url` to get the commit sha + repo url.
- Note: github repo urls are stripped of any sensitive information + are formatted. This code was copied from the datadog-ci
the `git.commit.sha` and `git.repository_url` tags are then added by default to the lambda functions.
if either of these commands fail, a warning will be printed, but deployment will continue.
users can turn off source code integration by setting the `sourceCodeIntegration` config value to false.
If users don't have the datadog github integration added, they will still need to import datadog-ci themselves and upload metadata. this will be documented in a future docs PR
- unused parameters in …

Enable source code integration within the CDK itself + add python support

---

common/constants.ts
common/interfaces.ts
common/redirect.ts
v1/.prettierrc
v1/integration_tests/lambda/example-java.java
v1/integration_tests/snapshots/correct-lambda-java-function-stack-snapshot.json
v1/integration_tests/snapshots/test-lambda-java-function-stack-snapshot.json
v1/integration_tests/stacks/lambda-java-function-stack.ts
v1/scripts/run_integration_tests.sh
v1/src/datadog.ts
v1/src/layer.ts
v1/test/redirect.spec.ts
v2/.prettierrc
v2/integration_tests/lambda/example-java.java
v2/integration_tests/snapshots/correct-lambda-java-function-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-java-function-stack-snapshot.json
v2/integration_tests/stacks/lambda-java-function-stack.ts
v2/scripts/run_integration_tests.sh
v2/src/datadog.ts
v2/src/layer.ts
v2/test/redirect.spec.ts

Adds support (cdk v1 & cdk v2) for adding the java tracing layer to lambda functions instrumented with the CDK.
Specifically, the `dd-trace-java` lambda layer will be added and the `AWS_LAMBDA_EXEC_WRAPPER=/opt/datadog_wrapper` env var will be set.
Only supports java8 corretto & java11
addresses [this opened issue/feature request](https://github.com/DataDog/datadog-cdk-constructs/issues/153).
Updated unit tests & integration tests.
I also built the cdk and manually tested both V1 & V2 on Python AND Typescript stacks.

Support adding Java layers

---

v2/.projen/deps.json
v2/.projenrc.js
v2/package.json
v2/yarn.lock

Updates the aws-cdk dependency for v2 of the datadog-cdk. Fixes our integration tests.
the pnpm package had a new release (8.0.0) which removed support for node14 which broke synth/deploy in some scenarios for the aws-cdk (v2). This broke our integration tests.
See here: https://github.com/aws/aws-cdk/issues/24820
Integration tests now pass.

Fix failing integration test

---

README.md
common/env.ts
common/interfaces.ts
v1/test/env.spec.ts
v2/test/env.spec.ts

Adds the field `apmFlushDeadline` which sets `DD_APM_FLUSH_DEADLINE_MILLISECONDS`.
This field allows users to determine when to submit spans before a timeout.
Configure custom deadline before a timeout. Which is available in both the tracers for Python and NodeJS.
Added unit tests.

feat: add `DD_APM_FLUSH_DEADLINE_MILLISECONDS` support

---

v2/scripts/publish_prod.sh

Just adds a link to the release script output
Easier to click the link
https://github.com/DataDog/datadog-cdk-constructs/tags

Add link to GH tags page in release output

---

common/datadogSharedLogic.ts
common/env.ts
common/interfaces.ts
v1/src/datadog.ts
v2/src/datadog.ts
v2/test/datadog.spec.ts

Lets users do the following (from [this issue](https://github.com/DataDog/datadog-cdk-constructs/issues/174)):
Instead of passing in an `apiKeySecretArn` or `apiKey`, users can create a Secret object and pass that in to Datadog:
```
const secret = Secret.fromSecretPartialArn(this, 'DatadogApiKeySecret', 'arn:aws:secretsmanager:us-west-123123123:secret:DATADOG_API_KEY');
const datadog = new Datadog(scope, 'Datadog', {
nodeLayerVersion: 91,
extensionLayerVersion: 43,
addLayers: true,
...
apiKeySecret: secret
...
});
```
- the `Secret.fromSecretPartialArn` is imported from `aws-cdk-lib/aws-secretsmanager`
With this secret object, we can grant lambda functions read access to the secret, so users don't have to manually grant secret read access to the lambda execution role.
Under the hood, we …

Automatically grant functions read access to a given aws secret

---

common/datadogSharedLogic.ts
v2/src/datadog.ts
v2/src/index.ts
v2/src/interfacesV2.ts
v2/test/datadog.spec.ts

[This PR](https://github.com/DataDog/datadog-cdk-constructs/issues/174) worked as a JS package, but produced a broken Python package. This was not caught in testing.
The issue stems from a bug with typescript intersection types compiled into python, [see here](https://github.com/DataDog/datadog-cdk-constructs/blob/2343119f325c942768291f1f05bbd292d5dc0c0a/v2/src/datadog.ts#L35) for the exact line.
This PR fixes this

Fix: auto grant secret read permissions python package bug

---

README.md

Adds a missing comma in the docs code example for auto grant secret read access

Fix missing comma in docs code example

---

common/interfaces.ts
common/layerSharedLogic.ts
v1/src/datadog.ts
v1/src/layer.ts
v1/test/datadog.spec.ts
v1/test/env.spec.ts
v1/test/forwarder.spec.ts
v1/test/index.spec.ts
v1/test/transport.spec.ts
v2/src/datadog.ts
v2/src/interfacesV2.ts
v2/src/layer.ts

Adds the optional parameter `useLayersFromAccount` || `use_layers_from_account` to allow our CDK to use DD Lambda layers of the same name published into the executing account. For this special case, we make sure the feature is region agnostic.
Work that is in line with https://github.com/DataDog/serverless-plugin-datadog/pull/386 
Tested manually v1 and v2 with node + python examples. Updated a handful of the unit tests for v1 since they were all failing with `ARNs must start with "arn:" and have at least 6 components` errors.

[SLS-3290] Allow cdk v1 + v2 to use layers from another account

---

v2/test/datadog.spec.ts
v2/test/env.spec.ts
v2/test/layer.spec.ts
v2/test/transport.spec.ts

Resolves console errors displayed when running v2 unit tests.
https://datadoghq.atlassian.net/browse/SLS-3061
Ran `yarn test` and confirmed that no more console errors were displayed in the unit test output.
Console errors were the result of a missing `nodeLayerVersion` or `pythonLayerVersion` parameter when initializing the Datadog CDK. The majority of the errors were resolved by adding the missing parameter.
One unit test asserted that the error messages are present when the parameters are missing so for this case the errors were resolved by mocking the log library to not display the error message in the console.

Resolve v2 unit test console errors

---

common/datadogSharedLogic.ts
v1/test/datadog.spec.ts
v2/test/datadog.spec.ts

Allow bypassing the site-check when the environment variable `DD_CDK_BYPASS_SITE_VALIDATION` is set to "true"
Datadog developers need a way to bypass the site-check to manually test the CDK tool on staging or any other custom site that is not in `siteList`.
I wrote new tests for v1 and v2 to check that the site check passes when using an invalid site and `DD_CDK_BYPASS_SITE_VALIDATION` is set.
This is not intended to be used by users and only for developing and testing purposes.

Allow bypassing site check

---

v2/package.json
v2/src/layer.ts
v2/test/assets/Dockerfile
v2/test/layer.spec.ts
v2/test/redirect.spec.ts

- Fixes the error brought up in https://github.com/DataDog/datadog-cdk-constructs/issues/185 by preventing the extension layer from being added to a Lambda container image
- Adds tests for the container image case
https://github.com/DataDog/datadog-cdk-constructs/issues/185
Deployed with example CDK Lambda container image project with the error no longer happening

Fix error when instrumenting Lambda container images 

---

v2/.projen/deps.json
v2/.projenrc.js
v2/integration_tests/snapshots/correct-lambda-function-arm-stack-snapshot.json
v2/integration_tests/snapshots/correct-lambda-function-stack-snapshot.json
v2/integration_tests/snapshots/correct-lambda-java-function-stack-snapshot.json
v2/integration_tests/snapshots/correct-lambda-nodejs-function-stack-snapshot.json
v2/integration_tests/snapshots/correct-lambda-python-function-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-function-arm-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-function-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-java-function-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-nodejs-function-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-python-function-stack-snapshot.json
v2/package.json
v2/yarn.lock

Bumps CDK version to 2.93
Snapshots needed to be regenerated but AFAICT only the order of keys in the json changed
https://github.com/DataDog/datadog-cdk-constructs/issues/208
Deployed with testing app

Bump CDK and @aws-cdk/aws-lambda-python-alpha to 2.93

---

v2/integration_tests/snapshots/correct-lambda-singleton-function-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-singleton-function-stack-snapshot.json
v2/integration_tests/stacks/lambda-singleton-function-stack.ts
v2/scripts/run_integration_tests.sh
v2/src/datadog.ts
v2/src/interfaces.ts
v2/test/index.spec.ts
v2/test/test-utils.ts

Adds support for Singleton functions.
https://datadoghq.atlassian.net/browse/SVLS-3474
* Added unit test to verify `addLambdaFunctions` handles Singleton functions as expected
* Added integration test for adding Datadog extension and layer to Singleton function
* `./v2/scripts/run_integration_tests.sh` (with `UPDATE_SNAPSHOTS-true` to generate snapshot for singleton function)
* Tested manually in sandbox
* `npx cdk --app lib/sample/index.js deploy`
The Lambda function in the SingletonFunction class is in the `lambdaFunction` property so before making any updates to Singleton functions the Lambda function is extracted from this `lambdaFunction` property.
* Updated `test-utils.findDatadogSubscriptionFilters` to properly handle Singleton functions in unit test
* Added singleton function …

adds support for singleton functions

---

examples/typescript-cdk-v2/lib/typescript_v2-stack.ts
examples/typescript-cdk-v2/package.json
examples/typescript-cdk-v2/yarn.lock
v2/src/constants.ts
v2/src/datadog.ts
v2/src/env.ts
v2/src/interfaces.ts
v2/test/datadog.spec.ts
v2/test/env.spec.ts

Adds support to configure the ASM product for Lamdba functions by injecting the relevant environment variable. Note that ASM can only be enabled if tracing is also enabled; failure to do so results in a validation error.
It makes it easier to onboard AppSec for Lambda and reduces the risk of misconfiguration.
Unit tests were added for the new features.

feat: ASM for Lambda configuration

---

v2/integration_tests/snapshots/correct-lambda-provided-arm-stack-snapshot.json
v2/integration_tests/snapshots/correct-lambda-provided-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-provided-arm-stack-snapshot.json
v2/integration_tests/snapshots/test-lambda-provided-stack-snapshot.json
v2/integration_tests/stacks/lambda-provided-arm-stack.ts
v2/integration_tests/stacks/lambda-provided-stack.ts
v2/scripts/run_integration_tests.sh
v2/src/constants.ts
v2/src/redirect.ts
v2/test/layer.spec.ts

Adds the Datadog Lambda extension to handlers using custom runtimes
Heard from a customer that this is not working
* Added unit tests
* Added integration tests
* Deployed a test golang Lambda with locally-built construct and was able to see data coming into Datadog through the extension

Add extension to Lambda handlers using custom runtimes

---

v2/src/layer.ts
v2/test/layer.spec.ts

1. Fixes an issue where java doesn't have an ARM layer
2. Cleans up our isNode/isArm logic.
3. Cleans up our error handling logic

[SLES-1529] Java doesn't have an arm layer, also clean up some code

---

v2/src/datadog.ts
v2/test/datadog.spec.ts
v2/test/env.spec.ts

We identified and fixed a similar issue in the serverless plugin where ASM config may inadvertently be applied to functions without the extension configured.
This would cause those functions to crash.

fix: Ensure ASM does not apply when the extension is not present

---

.projenrc.js
dist/go/ddcdkconstruct/Datadog.go
dist/go/ddcdkconstruct/Transport.go
dist/go/ddcdkconstruct/go.mod
package.json

Right now the Go module name configured is wrong. It doesn't include the path inside the directory: `dist/go`. As a result, in a Go project, when I tried to install this package, I got an error:
```
yiming.luo@COMP-J7WRL6274T go-hello % go get -u github.com/DataDog/datadog-cdk-constructs/dist/go/ddcdkconstruct
go: github.com/DataDog/datadog-cdk-constructs/dist/go/ddcdkconstruct@upgrade (v0.0.0-20240731210442-cae5a5626d82) requires github.com/DataDog/datadog-cdk-constructs/dist/go/ddcdkconstruct@v0.0.0-20240731210442-cae5a5626d82: parsing go.mod:
module declares its path as: github.com/DataDog/datadog-cdk-constructs/ddcdkconstruct
but was required as: github.com/DataDog/datadog-cdk-constructs/dist/go/ddcdkconstruct
```
Fix this error by adding `dist/go` to the module name.
1. Push this …

fix: Fix module name for Go

---

scripts/publish_prod.sh

After a new version of the Go package is published, pkg.go.dev won't pick up the new version immediately. For example, after I released version 1.14.0 to repo `datadog-cdk-construct-go`, [pkg.go.dev](https://pkg.go.dev/github.com/DataDog/datadog-cdk-constructs-go/ddcdkconstruct) still showed 1.13.0 as the latest version.
Make `publish_prod.sh` script make an explicit request to `proxy.golang.org` so they can pick up the latest version.
Refer to: https://pkg.go.dev/about#adding-a-package
This time I'm unable to test that it works because I already notified pkg.go.dev in another way, i.e. visiting https://pkg.go.dev/github.com/DataDog/datadog-cdk-constructs-go/ddcdkconstruct@v1.14.0 then clicking the Request button, which is the first way mentioned in …

chore: add script to make pkg.go.dev pick up new version

---

README.md

In `README.md`:
1. Add a Go icon which links to the package page on `pkg.go.dev`
2. fix the Go installation command
1. Check the rendered icon in README. It looks good. <img width="210" alt="image" src="https://github.com/user-attachments/assets/22ddebfc-9a90-44e2-b195-cae9ec705284">
- Click on it. It redirects to the right page.
2. Run the Go installation command. No error.
```
yiming.luo@COMP-J7WRL6274T go-stack % go get github.com/DataDog/datadog-cdk-constructs-go/ddcdkconstruct
go: downloading github.com/DataDog/datadog-cdk-constructs-go/ddcdkconstruct v1.14.0
go: downloading github.com/DataDog/datadog-cdk-constructs-go v0.0.0-20240813202855-e43af4f7c380
go: upgraded github.com/DataDog/datadog-cdk-constructs-go/ddcdkconstruct v1.13.0 => v1.14.0
yiming.luo@COMP-J7WRL6274T go-stack % …
```

chore: add Go icon and fix a command in README

---

src/datadog.ts
src/env.ts
src/forwarder.ts
src/layer.ts
src/redirect.ts

Add explicit return type for functions.
Most functions in the codebase don't have an explicit return type. Adding it would make code more readable, improving developer experience.
npm test

chore: Add return type for functions

---

src/constants.ts

Adds support for `provided.al2023` in the Lambda runtime lookup.
To fix issue https://github.com/DataDog/datadog-cdk-constructs/issues/282
npm test
See notes on the issue https://github.com/DataDog/datadog-cdk-constructs/issues/282

fix: add custom provided.al2023 to runtime lookup

---

.projen/tasks.json
.projenrc.js
examples/typescript-stack/lib/cdk-typescript-stack.ts
integration_tests/lambda/example-lambda.ts
integration_tests/stacks/lambda-function-arm-stack.ts
integration_tests/stacks/lambda-function-stack.ts
integration_tests/stacks/lambda-java-function-stack.ts
integration_tests/stacks/lambda-nodejs-function-stack.ts
integration_tests/stacks/lambda-python-function-stack.ts
integration_tests/stacks/lambda-singleton-function-stack.ts

Auto format some TypeScript files
The next PR (https://github.com/DataDog/datadog-cdk-constructs/pull/285) will touch lots of files, and saving those files on VS Code on my laptop will auto-format those files, mixing formatting changes and other changes in the same PR, so I want to separate out the formatting changes to this PR to make changes easier to review.
I can also disable "format on save" on my IDE, but I think it's a good thing to keep code in good format.
`npx projen build`, no error

chore: auto format some TypeScript files

---

src/constants.ts
src/datadog-lambda.ts
src/datadog.ts
src/env.ts
src/interfaces.ts

1. Rename: `DatadogProps` -> `DatadogLambdaProps`
2. Rename: `DefaultDatadogProps` -> `DatadogLambdaDefaultProps`
3. Rename: `DatadogStrictProps` -> `DatadogLambdaStrictProps`
4. Add a type alias `export type DatadogProps = DatadogLambdaProps;` so the renaming won't affect users
To make it cleaner to add `DatadogStepFunction` class later. Details in [[RFC] Changing API for Datadog CDK Construct](https://docs.google.com/document/d/1g3bFuhWUayvuS_aS6kOHe_CGECocd8IhoKmM9s4dPU0)
`npm test`

chore: rename Lambda related interfaces

---

.npmignore
.projenrc.js

Exclude the example stacks in `examples/` from the generated Go/Node/Python packages.
https://github.com/DataDog/datadog-cdk-constructs/issues/283 complains that there CVE security vulnerabilities in the example Go stack, so let's remove the examples and see if it works.
Steps:
- Run `npx projen build`
- Go to `dist/go`, `dist/js`, `dist/python` and unpack the generated `.tgz` packages
Result:
- the `examples/` directory is not included in the packages.
I'm unable to test this because I failed to reproduce the issue. I created docker images using the example Go stack, and used Amazon Inspector to scan it. However, none of the 21 findings (15 critical, 5 medium, 1 untriaged) are from to the CDK construct package. Most are from the `jsii-runtime-go` package. Example:
And excluding …

fix: exclude example stacks from package

---

src/constants.ts
src/datadog-lambda.ts
src/datadog.ts
src/env.ts
src/interfaces.ts

Reverts #288 
#294 
1. Make changes on the example Python stack to make it use `DatadogProps` https://github.com/DataDog/datadog-cdk-constructs/commit/480eed099a4836360e72365db6edcd1af1d43d36
2. Deploy the stack
Before:
- `cdk deploy` gives an error:
> ImportError: cannot import name 'DatadogProps' from 'datadog_cdk_constructs_v2'
After:
- `cdk deploy` runs successfully

fix: revert "chore: rename Lambda related interfaces (#288)"

---

examples/python-stack/cdk_python/cdk_python_stack.py
examples/python-stack/cdk_python/cdk_python_stack_base.py

Right now we have
```
class CdkPythonStack(Stack):
```
This PR adds a class `CdkPythonStackBase`, and makes:
```
class CdkPythonStackBase(Stack):
```
and
```
class CdkPythonStack(CdkPythonStackBase):
```
`CdkPythonStackBase` contains the setup of AWS resources, not related to Datadog.
`CdkPythonStack` contains Datadog instrumentation code.
I'm going to rename the interfaces like I did in https://github.com/DataDog/datadog-cdk-constructs/pull/288. To make sure both the new API and old API work, I will need to to write two stacks for testing the two APIs. The two stacks will share the non-Datadog setup code, so I'm putting this part in the base class.
`cdk deploy` successfully deploys the Python stack.

chore: Refactor example Python stack by extracting a base class

---

examples/typescript-stack/lib/cdk-typescript-stack-base.ts
examples/typescript-stack/lib/cdk-typescript-stack.ts

Right now
```
class CdkTypeScriptStack extends Stack
```
This PR adds a class `CdkTypeScriptStackBase`, and makes:
```
class CdkTypeScriptStackBase extends Stack
```
and
```
class CdkTypeScriptStack extends CdkTypeScriptStackBase
```
`CdkTypeScriptStackBase` contains the setup of AWS resources, not related to Datadog.
`CdkTypeScriptStack` contains Datadog instrumentation code.
I'm going to rename the interfaces like I did in https://github.com/DataDog/datadog-cdk-constructs/pull/288. To make sure both the new API and old API work, I will need to to write two stacks for testing the two APIs. The two stacks will share the non-Datadog setup code, so I'm putting this part in the base class.
`cdk deploy` successfully deploys the TypeScript stack.

chore: Refactor example typescript stack by extracting a base class

---

integration_tests/stacks/typescript/lambda-function-arm-stack.ts
integration_tests/stacks/typescript/lambda-function-stack-legacy-datadog-api.ts
integration_tests/stacks/typescript/lambda-function-stack.ts
integration_tests/stacks/typescript/lambda-java-function-stack.ts
integration_tests/stacks/typescript/lambda-nodejs-function-stack.ts
integration_tests/stacks/typescript/lambda-provided-arm-stack.ts
integration_tests/stacks/typescript/lambda-provided-stack.ts
integration_tests/stacks/typescript/lambda-python-function-stack.ts
integration_tests/stacks/typescript/lambda-singleton-function-stack.ts
scripts/run_integration_tests.sh

- `integration_tests/stacks/` contains a few example Typescript stacks
- `integration_tests/snapshots/` contains the expected snapshots generated from the stacks
- `scripts/run_integration_tests.sh` generates snapshots from the stacks, and compare the generated stacks with expected stacks
The test only covers TypeScript stacks. We want to cover Python and Go stacks as well to prevent issues like https://github.com/DataDog/datadog-cdk-constructs/issues/294, where the Python package was broken.
1. Move the Typescript stacks to a `typescript/` directory
2. Make `run_integration_tests.sh` check the language of each stack, instead of assuming all stacks are in Typescript. Make the script require that path of a typescript stack should be like `typescript/<name>.ts`.
Run `aws-vault exec …

chore: Refactor run_integration_tests.sh by adding stack language check

---

scripts/run_integration_tests.sh

`run_integration_tests.sh` runs `cdk synth` on a few example stacks, then compares the result with snapshots generated before, to check if a PR causes unexpected changes on the stack to be deployed.
Right now the test script uses 8 example stacks. A stack `lambda-function-stack-legacy-datadog-api.ts` was added in https://github.com/DataDog/datadog-cdk-constructs/pull/285, but it's not set up correctly to be used by the test script.
Make `run_integration_tests.sh` cover the new stack as well.
`aws-vault exec sso-serverless-sandbox-account-admin -- scripts/run_integration_tests.sh` runs successfully.

chore: Add a missing TypeScript stack to integration test

---

.github/workflows/integration_tests.yml
integration_tests/snapshots/correct-lambda_python_stack-snapshot.json
integration_tests/snapshots/test-lambda_python_stack-snapshot.json
integration_tests/stacks/python/lambda_python_stack.py
integration_tests/stacks/python/lambda_python_stack_base.py
integration_tests/stacks/python/requirements.txt
scripts/run_integration_tests.sh

Add a Python stack to integration tests, so that the test will compare the snapshots generated after vs before, to check if a PR causes unexpected changes on the stack to be deployed.
The stack was copied from `examples/python-stack`. I had to copy it because I was unable to find a way to just reference the existing stack.
Adding more tests to make it safer to deploy changes.

chore: Add integration test for Python stack

---

integration_tests/snapshots/correct-lambda-function-stack-legacy-datadog-api-snapshot.json
integration_tests/stacks/typescript/lambda-function-stack-legacy-datadog-api.ts

`correct-lambda-function-stack-legacy-datadog-api-snapshot.json` is empty. This is because the stack should be called `lambda-function-stack-legacy-datadog-api`, but it is `lambda-function-stack` from copy-paste.
Updates the stack name, so a snapshot can be created with the correct name.
The snapshot becomes not empty.

chore: Fix a stack in snapshot tests

---

scripts/run_integration_tests.sh

The snapshot test doesn't fail when a generated snapshot is empty. As a result, empty snapshots can be added for new stacks as "correct" snapshots, making the test unable to capture unexpected changes.
For example, https://github.com/DataDog/datadog-cdk-constructs/pull/309 fixed an empty snapshot.
Make the snapshot fail if a snapshot is empty.
Steps:
1. In the stack `lambda-function-stack-legacy-datadog-api.ts`, change the stack name to something random, e.g.:
```
const stack = new ExampleStack(app, "lambda-function-stack-legacy-datadog-api-2", { env: env });
```
so `lambda-function-stack-legacy-datadog-api.template.json` won't be generated and will be initialized as an empty file by the script.
2. Run `aws-vault exec sso-serverless-sandbox-account-admin -- …

chore: Make snapshot test fail when snapshot is empty

---

scripts/run_integration_tests.sh

The command `npx tsc --project tsconfig.json` compiles the TypeScript test stacks into JavaScript code. Right now it's run once for every stack, which is unnecessary.
Only run this command once at the beginning.
1. Run and time the snapshot tests: `time aws-vault exec sso-serverless-sandbox-account-admin -- scripts/run_integration_tests.sh`
Before:
> 60.37s user 6.44s system 116% cpu 57.561 total
After:
> 16.10s user 3.61s system 62% cpu 31.789 total

chore: Remove duplicate work in snapshot tests

---

examples/go-stack/app.go
examples/python-stack/app.py
examples/python-stack/cdk_python/cdk_python_lambda_old_api_stack.py
examples/typescript-stack/bin/index.ts
examples/typescript-stack/lib/cdk-typescript-lambda-old-api-stack.ts
examples/typescript-stack/lib/cdk-typescript-stack-base.ts
integration_tests/snapshots/correct-lambda_go_old_lambda_api_stack-snapshot.json
integration_tests/snapshots/correct-lambda_python_old_lambda_api_stack-snapshot.json
integration_tests/stacks/go/helpers.go
integration_tests/stacks/go/lambda_go_old_lambda_api_stack.go
integration_tests/stacks/go/main.go
integration_tests/stacks/python/.gitignore
integration_tests/stacks/python/lambda_python_old_lambda_api_stack.py
integration_tests/stacks/python/lambda_python_stack.py
scripts/run_integration_tests.sh
src/constants.ts
src/datadog-lambda.ts
src/datadog.ts
src/env.ts
src/interfaces.ts

Redoes https://github.com/DataDog/datadog-cdk-constructs/pull/288:
1. Rename: `DatadogProps` -> `DatadogLambdaProps`
2. Rename: `DefaultDatadogProps` -> `DatadogLambdaDefaultProps`
3. Rename: `DatadogStrictProps` -> `DatadogLambdaStrictProps`
4. For backward compatibility, add:
```
export interface DatadogProps extends DatadogLambdaProps {}
export const DatadogDefaultProps = DatadogLambdaDefaultProps;
export interface DatadogStrictProps extends DatadogLambdaStrictProps {}
```
5. Add an example Python stack and an example Go stack that use the new APIs (`DatadogLambda` and `DatadogLambdaProps`) to `examples/`. Also add these two stacks to `integration_tests/stacks` for snapshot tests.
To make it cleaner to add `DatadogStepFunction` class later. Details in [[RFC] Changing API for Datadog …

feat: Redo: Rename Lambda related interfaces

---

examples/step-functions-typescript-stack/.npmignore
examples/step-functions-typescript-stack/README.md
examples/step-functions-typescript-stack/bin/index.ts
examples/step-functions-typescript-stack/cdk.json
examples/step-functions-typescript-stack/lib/cdk-step-functions-typescript-stack.ts
examples/step-functions-typescript-stack/package.json
src/datadog-step-functions.ts
src/index.ts
src/interfaces.ts

1. Add a skeleton of `DatadogStepFunctions` class, which users will use to add Datadog monitoring for their Step Functions
2. Add an example TypeScript stack showing how to use this class in a CDK
- a large part of the stack was copied from the existing TypeScript stack for Lambda functions
For [SVLS-4394: Customers can instrument their Step Functions with CDK macro and SAM](https://datadoghq.atlassian.net/browse/SVLS-4394)
Followed the [internal wiki for testing local changes to CDK Construct](https://datadoghq.atlassian.net/wiki/spaces/SLS/pages/2723906703/Datadog+CDK+Constructs#Local-Changes)
After `cdk deploy`, a CloudFormation stack was deployed successfully, which includes a Lambda function and a Step Function, though Datadog monitoring is not set up for them.
Please comment on …

feat: add skeleton of step function class and example stack

---

README.md

Make example code in `README.md`
to use:
1. `DatadogLambda` instead of `Datadog`
2. `DatadogLambdaProps` instead of `DatadogProps`
The renaming is to make it cleaner to add `DatadogStepFunction` class later. Details in [[RFC] Changing API for Datadog CDK Construct](https://docs.google.com/document/d/1g3bFuhWUayvuS_aS6kOHe_CGECocd8IhoKmM9s4dPU0)

feat: update example doc to use DatadogLambda

---

examples/step-functions-typescript-stack/bin/index.ts
examples/step-functions-typescript-stack/lib/cdk-step-functions-typescript-stack.ts
src/datadog-step-functions.ts
src/interfaces.ts
test/datadog-step-functions.spec.ts

Enables setting up logging for a given state machine:
1. Set log level to ALL
2. Set includeExecutionData to true
3. Set destination log group (if not set already)
4. Add permissions to the state machine role to log to CloudWatch Logs
This is the first step of instrumenting a step function.
Passed the added tests.
Successfully deployed the example app `step-functions-typescript-stack`, which contains two stacks.

feat: [Step Function] Set up logging

---

src/datadog-lambda.ts

```
...
}
```
```
}
}
return;
} …
```

chore: Make helpers take one, not multiple Lambda functions (1/x)

---

examples/step-functions-typescript-stack/lib/cdk-step-functions-typescript-stack.ts
src/datadog-step-functions.ts
src/interfaces.ts
src/tag.ts
test/tags.spec.ts

Enables setting tags for the state machine, including DD tags and custom tags. For example, if the user passes these properties to Datadog:
```
const datadogSfn = new DatadogStepFunctions(this, "Datadog", {
env: "dev",
service: "my-service",
version: "1.0.0",
forwarderArn: process.env.DD_FORWARDER_ARN,
tags: "custom-tag-1:tag-value-1,custom-tag-2:tag-value-2",
});
datadogSfn.addStateMachines([stateMachine]);
```
Then the state machine will have these tags:
- `DD_ENV`: `env`
- `DD_SERVICE`: `my-service`
- `DD_VERSION`: `1.0.0`
- `custom-tag-1`: `tag-value-1`
- `custom-tag-2`: `tag-value-2`
This is one step of instrumenting a step function.
Passed the added test
Deployed the example stacks `step-functions-typescript-stack`. The tags are set as expected.
Need a stamp from Cloud Tracing team, …

feat: [Step Function] Set tags

---

examples/step-functions-typescript-stack/lib/cdk-step-functions-typescript-stack.ts
src/datadog-step-functions.ts
src/span-link.ts
test/span-link.spec.ts

Support merging Step Function traces with downstream LambdaInvoke step traces.
If the user constructs their state machine using:
```diff
const stateMachine = new sfn.StateMachine(this, "CdkTypeScriptTestStateMachine", {
definitionBody: sfn.DefinitionBody.fromChainable(
new tasks.LambdaInvoke(this, "MyLambdaTask", {
lambdaFunction: helloLambdaFunction,
+         payload: sfn.TaskInput.fromObject(DatadogStepFunctions.buildLambdaPayloadToMergeTraces()),
}).next(new sfn.Succeed(this, "GreetedWorld")),
),
});
```
Then we will add these fields to their Lambda payload:
```
"Execution.$": "$$.Execution",
"State.$": "$$.State",
"StateMachine.$": "$$.StateMachine",
```
which will enable merging Step Function traces with Lambda traces.
Passed the added unit tests.
1. Deploy the example typescript …

feat: Support SFN->Lambda trace merging

---

examples/step-functions-typescript-stack/lib/cdk-step-functions-typescript-stack.ts
src/datadog-step-functions.ts
src/span-link.ts
test/span-link.spec.ts

Support merging Step Function traces with downstream StepFunction StartExecution task traces.
If the user constructs the task using:
```
const invokeChildStateMachineTask = new tasks.StepFunctionsStartExecution(this, "InvokeChildStateMachineTask", {
stateMachine: childStateMachine,
input: sfn.TaskInput.fromObject(
DatadogStepFunctions.buildStepFunctionTaskPayloadToMergeTraces({ "custom-key": "custom-value" }),
),
});
```
then we will add these fields to the input to the State Machine:
```
"CONTEXT.$": "$$['Execution', 'State', 'StateMachine']"
```
Passed the added unit tests.
1. Deploy the example typescript step function stack
2. Run the State Machine once
1. The `CONTEXT.$1 field is added to Step Function step input
2. The flame graph of the step function also shows the flame graph of …

feat: Support StepFunction->StepFunction trace merging

---

test/datadog-step-functions.spec.ts
test/env.spec.ts

1. Change the way to set up a State Machine in Jest tests so this warning won't be printed when we run `npm test`:
2. Pass a required Datadog prop `nodeLayerVersion` so this error-level log won't be printed:
Run `npm test`. The output is now clean:

chore: Fix warnings in tests

---

integration_tests/snapshots/correct-step_functions_go_stack-snapshot.json
integration_tests/stacks/go/main.go
integration_tests/stacks/go/step_functions_go_stack.go
scripts/run_integration_tests.sh

Add a snapshot test for a Go step function stack to ensure future changes don't unintentionally change the synthesized CloudFormation template.

chore: Add snapshot test for Go step function stack

---

src/datadog-lambda.ts
src/layer.ts
test/layer.spec.ts

```
...
}
```
```
}
}
return;
} …
```

chore: Make helpers take one, not multiple Lambda functions (2/x)

---

src/datadog-lambda.ts
src/forwarder.ts
test/forwarder.spec.ts

```
...
}
```
```
}
}
return;
} …
```

chore: Make helpers take one, not multiple Lambda functions (4/x)

---

README.md

1. Put a large part of README into a section `Lambda` because I'll soon add a `Step Function` section.
2. Made various other updates.

chore: Refactor README to prepare for adding step function doc

---

README.md

Adds doc for Step Functions to README, including:
1. how to instrument Step Functions in TypeScript, Python and Go
2. how to merge traces with downstream Step Functions or Lambda functions in the three languages
3. explanation of params
4. a short explanation of what the construct does
5. troubleshooting guide for one issue

chore: Add Step Function section to README

---

integration_tests/snapshots/correct-step-function-stack-snapshot.json
integration_tests/snapshots/correct-step_functions_go_stack-snapshot.json
integration_tests/snapshots/correct-step_functions_python_stack-snapshot.json
src/constants.ts
src/tag.ts
test/tags.spec.ts

When instrumenting a state machine, sets `DD_TRACE_ENABLED` tag to `true`. This is needed to enable tracing. 
Aligned with @nine5two7 that we always set it to true for now. If any customer wants to customize it, we can support it later.
1. Passed the touched jest test.
2. Run `UPDATE_SNAPSHOTS=true aws-vault exec sso-serverless-sandbox-account-admin -- ./scripts/run_integration_tests.sh`, and the snapshots in the snapshot tests are updated.
1. Deploy the example stack `step-functions-typescript-stack`.
2. Run the state machine from AWS UI.
1. On AWS UI, this tag is added:
2. Traces are shown on Datadog app

feat: Set DD_TRACE_ENABLED tag on state machine

---

integration_tests/snapshots/correct-step-function-stack-snapshot.json
integration_tests/snapshots/correct-step_functions_go_stack-snapshot.json
integration_tests/snapshots/correct-step_functions_python_stack-snapshot.json
src/tag.ts
test/tags.spec.ts

When instrumenting a state machine, set a tag like `dd_cdk_construct:1.19.0`, similar to the practice for Lambda in CDK and for Step Functions in CI (`dd_sls_ci` tag) and Serverless Plugin (`dd_sls_plugin` tag).
1. Passed the touched jest test
2. Updated the snapshots in snapshot tests

feat: Set dd_cdk_construct version tag on state machine

---

src/datadog-lambda.ts
src/env.ts
test/datadog-lambda.spec.ts

```
...
}
```
```
}
}
return;
} …
```

chore: Make helpers take one, not multiple Lambda functions (5/x)

---

src/datadog-lambda.ts
src/env.ts

```
...
}
```
```
}
}
return;
} …
```

chore: Make helpers take one, not multiple Lambda functions (6/x)

---

src/datadog-lambda.ts
src/transport.ts

```
...
}
```
```
}
}
return;
} …
```

chore: Make helpers take one, not multiple Lambda functions (7/x)

---

src/datadog-lambda.ts
src/layer.ts
test/datadog-lambda.spec.ts
test/layer.spec.ts

1. If Lambda runtime is unsupported, e.g. if it's an unresolved token, then abort instrumenting this Lambda function.
2. Change the required AWS CDK version from 2.134.0 to 2.146.0, so the unresolved token case can be tested.
Right now, even if Node runtime is not supported, we still proceed with the rest of the steps of instrumentation. As a result, Lambda execution may fail because it can't find a Datadog wrapper that's supposed to be in the Lambda layer.
More in https://github.com/DataDog/datadog-cdk-constructs/issues/314
1. Make changes on the example TypeScript Lambda stack, so it uses an unresolved runtime https://github.com/DataDog/datadog-cdk-constructs/commit/793365b7affd281dbb42d38f417c8ee76aeb4127
3. Deploy the stack
1. A warning message is created:
2. Lambda function doesn't …

fix: Abort instrumenting Lambda if runtime is unsupported

---

.github/CODEOWNERS

Changing code owner from Serverless team to serverless-onboarding-enablement subteam
1. Onboarding and Enablement team is a more specific owner. 
2. Team members will be added as a reviewer in a Round Robin way.

chore: Change code owner to ONE team

---

src/datadog-lambda.ts
src/env.ts
test/datadog-lambda.spec.ts

Add the ability to override the git sha and repo url to make snapshot testing easier.
Requested by a customer in  https://github.com/DataDog/datadog-cdk-constructs/issues/359
* Unit tests
This PR allows you to override the git commit sha without having to modify your stack code, other than making the datadog lambda public on your stack.  From a code snippet from the issue, adding the new line will make the snapshot consistent
```
test('Snapshot', () => {
const app = new App();
const stack = new SomeStack(app, 'test', {
env: {
account: '0123456789012',
region: 'us-east-1',
},
});
// New line
stack.datadogLambda.overrideGitMetadata("fake-sha");
const template = Template.fromStack(stack);
expect(template.toJSON()).toMatchSnapshot();
});
```

chore: Add git sha and url overrides

---

scripts/publish_prod.sh

After we updated various dependencies, the name of the tarball of Python package is changed from something like `datadog-cdk-constructs-v2-2.0.0.tar.gz` to `datadog_cdk_constructs_v2-2.0.0.tar.gz` (hyphen to underscore).
As a result, the `publish_prod.sh` script, which assumes the old name format, is not working properly.
Updates the expected Python tarball name to be consistent with its real new name.
To test in prod by releasing v2-2.0.0.

fix: Change Python tarball name in publish_prod.sh

---

integration_tests/snapshots/correct-lambda_python_stack-snapshot.json
integration_tests/snapshots/correct-step_functions_python_stack-snapshot.json
integration_tests/stacks/python/requirements.txt

Upgrade `aws-cdk-lib` used by the Python stacks in snapshot tests from `2.134.0` to `2.146.0`.
The next PR will make these stacks use `v2-2.0.0` of `datadog-cdk-constructs`, which requires using `2.146.0`. Updating to `2.146.0` causes changes in shapshots, so this PR separates them out to make it clear that these changes are not caused by updating `datadog-cdk-constructs`.
The example Python stacks `examples/python-stack` and `examples/step-functions-python-stack` can still deploy with `aws-cdk-lib 2.146.0`

chore: Upgrade CDK version in Python snapshot tests

---

.github/workflows/build.yml
.github/workflows/integration_tests.yml

The GitHub Action `actions/cache` v2 is deprecated, making some actions fail to run. ([sample run](https://github.com/DataDog/datadog-cdk-constructs/actions/runs/13659434768/job/38186855499))
Upgrade `actions/cache` to v4.2.1, similar to Serverless Plugin (https://github.com/DataDog/serverless-plugin-datadog/pull/577)
The GitHub actions run successfully.

chore: Upgrade actions/cache to v4.2.1

---

README.md
integration_tests/snapshots/correct-lambda-function-arm-stack-snapshot.json
integration_tests/snapshots/correct-lambda-function-stack-snapshot.json
integration_tests/snapshots/correct-lambda-nodejs-function-stack-snapshot.json
integration_tests/snapshots/correct-lambda-singleton-function-stack-snapshot.json
integration_tests/stacks/typescript/lambda-function-arm-stack.ts
integration_tests/stacks/typescript/lambda-function-stack.ts
integration_tests/stacks/typescript/lambda-nodejs-function-stack.ts
integration_tests/stacks/typescript/lambda-singleton-function-stack.ts
scripts/run_integration_tests.sh
src/sample/index.ts
src/sample/index_cdk_v2_test.ts
test/datadog-lambda.spec.ts
test/env.spec.ts
test/forwarder.spec.ts
test/index.spec.ts
test/layer.spec.ts
test/tags.spec.ts
test/transport.spec.ts

The latest version of CDK Construct requires node.js version 18.18 or above, but many tests and examples are still using v14 or v16. This PR makes them use v18.
Passed all unit tests and integration tests.

chore: Use Node 18 in tests and examples

---

src/datadog-lambda.ts
test/datadog-lambda.spec.ts

Add the ability to also use a context variable for the git SHA override so there isn't a need to expose the datadog lambda on the stack.
Issue: https://github.com/DataDog/datadog-cdk-constructs/issues/359
All automated tests still pass, added a unit test for this

feat: Add context variable for git sha override

---

.projenrc.js
examples/go-stack/.gitignore
package.json

Go package fails to be published. When I run `publish_prod.sh`, this line:
https://github.com/DataDog/datadog-cdk-constructs/blob/a647447a3d5539cba7614d7bf78695aeac675877/scripts/publish_prod.sh#L127
prints:
> No modules detected. Skipping
This is because https://github.com/DataDog/datadog-cdk-constructs/pull/366 incorrectly added `/v2` suffix to the `moduleName`:
https://github.com/DataDog/datadog-cdk-constructs/blob/a647447a3d5539cba7614d7bf78695aeac675877/.projenrc.js#L23-L26
Now it doesn't seem to me that the `/v2` suffix is needed.
Remove the `/v2` suffix from Go moduleName to fix Go package publish.
Steps:
1. Run `GITHUB_TOKEN=$GITHUB_TOKEN npx -p publib@latest publib-golang`. 
Result:
1. A commit with tag `ddcdkconstruct/v2.2.0` is pushed to `datadog-cdk-constructs-go` repo: …

fix: Fix go package publish for v2-2.x.x

---

test/ecs/fargate/agent.spec.ts
test/ecs/fargate/apm-dsd.spec.ts
test/ecs/fargate/cws.spec.ts
test/ecs/fargate/logging.spec.ts
test/ecs/fargate/utils.spec.ts
test/ecs/utils.spec.ts

Increase the coverage on the unit tests for the Datadog ECS Fargate construct.
Improving reliability and preventing misconfigurations in user-defined properties.
N/A
N/A

chore(test): DatadogECSFargate unit test coverage

---

src/sample/ecs_fargate/index.ts

Adds an essential container to the task definition
When users attempt to use the ecs_fargate sample, an error will be thrown because there's no essential container in the task.
`cdk deploy` without errors
N/A

fix(docs): Add essential container to example

---

src/ecs/fargate/utils.ts

Prevents customers from enabling CWS on windows hosts.
The CWS Fargate solution requires `SYS_PTRACE` linux capabilities. This doesn't exist on Windows. Thus, this causes errors when trying to deploy a task on windows with containers requesting permissions that don't exist.
N/A
N/A

fix: Block CWS configuration on windows

---

src/ecs/fargate/environment.ts

Updates the Agent install tool information to accurately reflect the CDK construct and version.
Previously, the install info would default to the docker daemon that installs the container. 
N/A
N/A

chore: Track agent install info [CONTP-776]

---

src/ecs/fargate/datadog-ecs-fargate.ts
test/ecs/fargate/agent.spec.ts

Fixes #433 
This PR changes the docker labelling in the Fargate ECS construct to align to the Unified Service Tagging [documentation](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging?tab=ecs#configuration-1) 
Ensure monitoring features work out of the box as documented.
Manually tested the two labelling styles on a personal ECS project to confirm that the documentation was correct and that the labelling style used by the construct does not work.
Updated unit test to expect corrected label names.

fix(DatadogECSFargate): use correct UST docker labels

---

.github/workflows/build.yml

This PR removes the `Authenticate Docker to Amazon ECR` step from CI `test` jobs. 
We don't need docker access for these tests. The integration tests do, but they authenticate separately within the script. 
CI passes.

chore: Remove "Authenticate Docker to Amazon ECR" step from test jobs

---

yarn.lock

Run yarn upgrade to get a new version of form-data, which dependabot gave us a security warning for versions >= 3.0.0 and < 3.0.4.  The relevant section of this is in line 2505 of the yarn.lock file. 
Github security issue: https://github.com/DataDog/datadog-cdk-constructs/security/dependabot/107
Running git diff origin/main gives us the diff
```
> git diff origin/main |grep "form-data"
form-data@^3.0.0:
-  resolved "https://registry.yarnpkg.com/form-data/-/form-data-3.0.3.tgz#{Hash removed since github thinks its a secret}"
+  resolved "https://registry.yarnpkg.com/form-data/-/form-data-3.0.4.tgz#{Hash removed since github thinks its a secret}"
```

chore: Run yarn upgrade

---

.github/workflows/upgrade.yml
.gitignore
.projen/deps.json
.projenrc.js
package.json
scripts/upgrade-cdk.js
yarn.lock

Automate the cdk upgrade flow.  To do this I created a script to parsed the cdk version out of the projen rc file, then check the npm version from 1 month ago.  I chose that because that's the minimum version that someone needs, so 1 month behind seemed like a middle ground between being recent enough and not having someone have to go back and forth between upgrading the datadog cdk constructs and cdk versions, if they're doing some kind of weekly upgrade like we usually have.  Let me know if you prefer a different value for this.
The script has to be included in the github upgrade workflow, so we have to overwrite it in projen since its managed for us.
Projen docs about this: https://projen.io/docs/project-types/aws-cdk-construct-library/#depending-on-aws-cdk-lib
The CDK version is …

chore: Automate cdk upgrade

---

.projen/tasks.json
.projenrc.js
examples/ecs/typescript-stack/package.json
examples/step-functions-typescript-stack/package.json
test/datadog-lambda.spec.ts

Allow the unit tests to work in gitlab.  There is something about our tests that is probably getting re used when we may not intend to, or something that isn't getting reset properly.  This was making the tests hang in gitlab, I'm not sure why but for now lets set run in band to make it run sequentially. This takes longer but is consistent.
Also change the github URL to match either the github or the gitlab url, with the .git at the end being optional.
Modify the names of the example stacks os that they don't overlap as well, this was giving us a warning.
Moving release to gitlab
* JIRA: https://datadoghq.atlassian.net/browse/SVLS-7287
* Passing gitlab job: https://gitlab.ddbuild.io/DataDog/datadog-cdk-constructs/-/jobs/1079139184
* Github / Gitlab issue: …

chore: Allow unit tests to run in gitlab

---

scripts/create_release.sh

Add a line to update the version.json file in the create_release script. This is needed both to keep it up to date, and to allow us to use a non empty PR to approve releases.
Also add chore: to the prefix of the commit so it gets added to the PR title to keep the PR title linter happy.
Updating release process
Updated script used for this release commit - https://github.com/DataDog/datadog-cdk-constructs/pull/474
JIRA: https://datadoghq.atlassian.net/browse/SVLS-7287

chore: Add version.json update to create release script

---

src/ecs/fargate/README.md
src/ecs/fargate/datadog-ecs-fargate.ts
src/ecs/fargate/interfaces.ts
test/ecs/fargate/logging.spec.ts

Adds a `fireLensLogDriver: FireLensLogDriver` field to `FluentbitConfig` which is used as the log driver in-place of creating our own driver with the `logDriverConfig`.
Customer request #465 asking for `ecs.FireLensLogDriver` to be an exposed option in the dd cdk construct.
1. Unit tests added in `logging.spec.ts` and CI is 🟢 
2. Manually QA'd to confirm user configured `fireLensLogDriver` is used on creation.

feat(CONTP-922): Expose ability to provide custom ecs.FireLenseLogDriver upon log driver creation
